# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    owner:
                        password: foo
                        roles: ROLE_SUPER_ADMIN
                    maintainer:
                        password: foo
                        roles: ROLE_ADMIN

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        # to active the security write: pattern: ^/(_(profiler|wdt)|css|images|js)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/remote, roles: ROLE_ADMIN }